"""initial schema

Revision ID: 2199fca41f00
Revises: 
Create Date: 2026-08-29 12:45:31.851139

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2199fca41f00'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('airline',
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_table('airport',
    sa.Column('airport_id', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('city', sa.String(length=50), nullable=False),
    sa.Column('country', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('airport_id')
    )
    op.create_table('customer',
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('building_num', sa.String(length=20), nullable=True),
    sa.Column('street', sa.String(length=100), nullable=True),
    sa.Column('city', sa.String(length=50), nullable=True),
    sa.Column('state', sa.String(length=50), nullable=True),
    sa.Column('phone_num', sa.String(length=10), nullable=True),
    sa.Column('passport_number', sa.String(length=50), nullable=True),
    sa.Column('passport_expiration', sa.Date(), nullable=True),
    sa.Column('passport_country', sa.String(length=50), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('email')
    )
    op.create_table('airline_staff',
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('f_name', sa.String(length=50), nullable=False),
    sa.Column('l_name', sa.String(length=50), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('airline_name', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['airline_name'], ['airline.name'], ),
    sa.PrimaryKeyConstraint('username')
    )
    op.create_table('airplane',
    sa.Column('airline_name', sa.String(length=50), nullable=False),
    sa.Column('id', sa.String(length=20), nullable=False),
    sa.Column('num_seats', sa.Integer(), nullable=False),
    sa.Column('manufacturing_co', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['airline_name'], ['airline.name'], ),
    sa.PrimaryKeyConstraint('airline_name', 'id')
    )
    op.create_table('email',
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['username'], ['airline_staff.username'], ),
    sa.PrimaryKeyConstraint('username', 'email')
    )
    op.create_table('flight',
    sa.Column('airline_name', sa.String(length=50), nullable=False),
    sa.Column('flight_no', sa.String(length=20), nullable=False),
    sa.Column('departure_date_and_time', sa.DateTime(), nullable=False),
    sa.Column('departure_airport_id', sa.String(length=10), nullable=False),
    sa.Column('arrival_airport_id', sa.String(length=10), nullable=False),
    sa.Column('arrival_date_and_time', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('base_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('airplane_airline_name', sa.String(length=50), nullable=True),
    sa.Column('airplane_id', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['airline_name'], ['airline.name'], ),
    sa.ForeignKeyConstraint(['airplane_airline_name', 'airplane_id'], ['airplane.airline_name', 'airplane.id'], ),
    sa.ForeignKeyConstraint(['arrival_airport_id'], ['airport.airport_id'], ),
    sa.ForeignKeyConstraint(['departure_airport_id'], ['airport.airport_id'], ),
    sa.PrimaryKeyConstraint('airline_name', 'flight_no', 'departure_date_and_time')
    )
    op.create_table('phone_num',
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('phone_num', sa.String(length=10), nullable=False),
    sa.ForeignKeyConstraint(['username'], ['airline_staff.username'], ),
    sa.PrimaryKeyConstraint('username', 'phone_num')
    )
    op.create_table('review',
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('airline_name', sa.String(length=50), nullable=False),
    sa.Column('flight_no', sa.String(length=20), nullable=False),
    sa.Column('departure_date_and_time', sa.DateTime(), nullable=False),
    sa.Column('rate', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['airline_name', 'flight_no', 'departure_date_and_time'], ['flight.airline_name', 'flight.flight_no', 'flight.departure_date_and_time'], ),
    sa.ForeignKeyConstraint(['email'], ['customer.email'], ),
    sa.PrimaryKeyConstraint('email', 'airline_name', 'flight_no', 'departure_date_and_time')
    )
    op.create_table('ticket',
    sa.Column('ticket_id', sa.String(length=20), nullable=False),
    sa.Column('sold_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('card_type', sa.String(length=20), nullable=True),
    sa.Column('card_num', sa.String(length=20), nullable=True),
    sa.Column('name_on_card', sa.String(length=50), nullable=True),
    sa.Column('card_expiry_date', sa.Date(), nullable=True),
    sa.Column('airline_name', sa.String(length=50), nullable=False),
    sa.Column('flight_no', sa.String(length=20), nullable=False),
    sa.Column('departure_date_and_time', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['airline_name', 'flight_no', 'departure_date_and_time'], ['flight.airline_name', 'flight.flight_no', 'flight.departure_date_and_time'], ),
    sa.PrimaryKeyConstraint('ticket_id')
    )
    op.create_table('purchases',
    sa.Column('ticket_id', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('date_and_time', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['email'], ['customer.email'], ),
    sa.ForeignKeyConstraint(['ticket_id'], ['ticket.ticket_id'], ),
    sa.PrimaryKeyConstraint('ticket_id', 'email')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('purchases')
    op.drop_table('ticket')
    op.drop_table('review')
    op.drop_table('phone_num')
    op.drop_table('flight')
    op.drop_table('email')
    op.drop_table('airplane')
    op.drop_table('airline_staff')
    op.drop_table('customer')
    op.drop_table('airport')
    op.drop_table('airline')
    # ### end Alembic commands ###
